### ISSUE TITLE
ERR_INVALID_ARG_TYPE('superCtor', 'Function', superCtor)

### ISSUE THREAD

**Issue by lil5** [andrew-medvedev/ftpd-cli#1]
```
ftpd-cli -D $(pwd)
util.js:1347
    throw new ERR_INVALID_ARG_TYPE('superCtor', 'Function', superCtor);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "superCtor" argument must be of type Function. Received type undefined
    at Object.inherits (util.js:1347:11)
    at Object.<anonymous> (/home/lil5/.config/yarn/global/node_modules/ftpd/lib/ftpd.js:67:6)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/home/lil5/.config/yarn/global/node_modules/ftpd-cli/lib/ftpd-cli.js:4:12)
```

**Comment by Silberling** [comment]
Same here. Using ubuntu and alpine docker container latest and stable.

**Comment by arthurvaverko-kaltura** [comment]
any updates on this ? i get the same using the lib.
